version: "3.8"

services:

  # nginx:
  #   build: ./requirements/nginx/
  #   ports:
  #   - "443:443"
  #   env_file: .env

  wordpress:
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
    - /home/dfranke/data/wordpress/:/var/www.html/
