version: "3.8"
services:

  nginx:
    image: nginx:latest
    build: ./requirements/nginx/
    ports:
      - "443:443"
    env_file: .env
    restart: on-failure
    volumes:
      - ~/dfranke/data/wordpress/:/var/www/html/
      #ON SCHOOL MAC:
      # - /home/dfranke/data/wordpress/:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    build: ./requirements/wordpress/
    env_file: .env
    restart: on-failure
    volumes:
      - ~/dfranke/data/wordpress/:/var/www/html/
      #ON SCHOOL MAC:
      # - /home/dfranke/data/wordpress/:/var/www/html/
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    build: ./requirements/mariadb/
    env_file: .env
    restart: on-failure
    volumes:
      - ~/dfranke/data/mariadb/:/var/lib/mysql/
      #ON SCHOOL MAC:
      # - /home/dfranke/data/mariadb/:/var/lib/mysql/
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge
