version: "3.8"
services:

  nginx:
    image: nginx:latest
    build: ./requirements/nginx/
    ports:
      - "443:443"
    env_file: .env
    restart: on-failure
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    build: ./requirements/wordpress/
    env_file: .env
    restart: on-failure
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    build: ./requirements/mariadb/
    env_file: .env
    restart: on-failure
    volumes:
      - mdb_volume:/var/lib/mysql/
    networks:
      - inception

volumes:
  wp_volume:
    name: wp_volume
    driver_opts:
      type: none
      o: bind
      #ON LINUX:
      device: /home/dfranke/data/wordpress/
      #ON MAC:
      #device: /Users/dfranke/data/wordpress/
  mdb_volume:
    name: mdb_volume
    driver_opts:
      type: none
      o: bind
      #ON Linux:
      device: /home/dfranke/data/mariadb/
      #ON MAC:
      #device: /Users/dfranke/data/mariadb/

networks:
  inception:
    name: inception
    driver: bridge
